twingly/twingly-amqp

- README.md
- lib/twingly/amqp.rb
- lib/twingly/amqp/subscription.rb
- twingly-amqp.gemspec
close #4
Added a class for subscribing to queues. The code is roughly the same as in chapman and zambezi.
Tested it by using `rabbitmqadmin`:
```shell
$ rabbitmqadmin declare exchange name=binlog-test type=topic
$ bundle console
> s = Twingly::AMQP::Subscription.new(queue_name: "testing-twingly-amqp", routing_key: "testing.#", exchange_topic: "binlog-test")
> s.subscribe do |message|
>   puts message
> end
```
```shell
$ rabbitmqadmin publish exchange=binlog-test routing_key="testing.test" payload='{"message": "hello!"}'
```
Tests for this would be nice, but I don't know how to do. I don't know how you should test `Subscription#subscribe` since it blocks the starting thread.
> AMQP subscription

- README.md
- lib/twingly/amqp.rb
- lib/twingly/amqp/connection.rb
- lib/twingly/amqp/ping.rb
- lib/twingly/amqp/session.rb
- lib/twingly/amqp/subscription.rb
- spec/amqp_queue_context.rb
- spec/twingly/connection_spec.rb
- spec/twingly/session_spec.rb
close #10
* `Session` - The class which sets up the amqp connection (is used by `Connection.instance`) 
* `Connection.options=` - can be used to set amqp hosts if they are not stored in ENV.
* `Connection.instance` 
* Creates a `Session` object the first time its called 
* Returns the same amqp connection (`session.connection`) each time its called
Took inspiration for the singleton pattern from http://stackoverflow.com/a/5259578
> Make connection class a singleton

- README.md
- lib/twingly/amqp/message.rb
- lib/twingly/amqp/subscription.rb
- spec/twingly/message_spec.rb
- spec/twingly/subscription_spec.rb
close #13
`subscriber.subscribe` gives an instance of the message class to the block instead of just the payload.
Makes it possible for the client to requeue and discard messages, and read the messages metadata etc.
> Create class for handling messages

- README.md
- lib/twingly/amqp/session.rb
- spec/twingly/session_spec.rb
- twingly-amqp.gemspec
Sends all options set in `Twingly::AMQP::Connection.options=` directly to Bunny. Needed for https://github.com/twingly/ganges/pull/44
close #25
> Allow more options

- README.md
- lib/twingly/amqp/pinger.rb
- spec/twingly/pinger_spec.rb
RabbitMQ cannot change queue-length and queue-message-ttl, the queue has to be deleted and then redeclared.
We wanted to be able to change this value easily, so we had to use per-message-ttl instead.
This is needed for the queue between norrstrom and klondike.
see https://trello.com/c/Setqn4Fd
> Set expiration per ping

- README.md
- lib/twingly/amqp/pinger.rb
- spec/integration/twingly/amqp/pinger_spec.rb
- spec/integration/twingly/amqp/session_spec.rb
Fix #42.
I took the easy sleeping route here as that's what we did
in all other tests.
I think it could be better to check the queue length
something like "wait until we can see message on queue" but I couldn't find
a, simple, reliable solution, during my tests I would, sometimes, end up with for-ever sleeping threads.
I believe there are timing issues at hand that are hard to "quick fix".
> Minor improvements and fix unreliable test case

- lib/twingly/amqp/pinger.rb
- spec/integration/twingly/amqp/pinger_spec.rb
- spec/integration/twingly/amqp/subscription_spec.rb
Close #44. Makes spec run on about 20% of the time of before :-).
Can be tidied up when we can publish to exchanges (#12).
> Remove sleeping in specs

- CHANGELOG.md
- README.md
Instructions taken from https://github.com/twingly/twingly-url#release-workflow.
Close #52.
> Improve release instructions and update change log

- README.md
- lib/twingly/amqp/subscription.rb
- spec/integration/twingly/amqp/subscription_spec.rb
I didn't want to duplicate all tests from `#each_message`, so I just copied the one I felt was most important (the one that makes sure it can receive a message from rabbitmq).
close #29
> Non-blocking subscribe (#on_each_message)

- examples/default_exchange_publisher.rb
- examples/topic_exchange_publisher.rb
- lib/twingly/amqp/pinger.rb
- lib/twingly/amqp/subscription.rb
- spec/integration/twingly/amqp/connection_spec.rb
- spec/integration/twingly/amqp/pinger_spec.rb
- twingly-amqp.gemspec
Takes care of CVE-2017-8418: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-8418
Also let RuboCop autocorrect everything it finds.
> Require RuboCop >= 0.49

- lib/twingly/amqp/subscription.rb
The call was accidentally removed in https://github.com/twingly/twingly-amqp/commit/22c799377a17274475c82e7e49fa7cabb62843db#diff-dad5e21a79b90b462ebf9695f101a6dbL37
The "faulty" version has already been released (as 4.3.0) and has now been used in a few projects for some time.
Since the signal_trap method it isn't called and we don't want the trap code in the gem anyways I removed it.
close #63
> Remove unused signal trap code

- lib/twingly/amqp/session.rb
- twingly-amqp.gemspec
Looks like i's included in the 2.6.2 release of bunny. See https://github.com/ruby-amqp/bunny/commit/565b5985f4d4ebf9980a5741e82b6ea9a823eacc
Close #57.
> Remove workaround for frozen arrary bug

- README.md
- lib/twingly/amqp/ping_options.rb
- spec/integration/twingly/amqp/pinger_spec.rb
- spec/unit/twingly/amqp/ping_options_spec.rb
Allows you to send any options in each ping message. This makes it easier for users of this gem to add new options in the future as no changes has to be made to twingly-amqp then.
Related to twingly/norrstrom#123
> Allow custom options in ping message

- README.md
- lib/twingly/amqp/subscription.rb
- spec/integration/twingly/amqp/subscription_spec.rb
Kept the old name of the parameter (routing_key), because changing it would have been a breaking change.
There's only one project in which we will use the "multiple routing keys" feature, so I think I can live with this name.
close #69
> Make it possible to subscribe using multiple routing keys

- spec/integration/twingly/amqp/default_exchange_publisher_spec.rb
- spec/integration/twingly/amqp/topic_exchange_publisher_spec.rb
- spec/publisher_examples.rb
Moved all duplicated specs from the two publishers into shared examples.
Related to the changes made in #73
In preparation of #71 (so we only have to update the specs in one place when solving it)
> DRY up publisher specs

- .travis.yml
Dropping Ruby 2.2 as it's unsupported and we do not use it.
> Use more recent rubies on Travis

- lib/twingly/amqp/publisher.rb
- spec/publisher_examples.rb
This changes the behaviour a bit, so a major version bump is needed for this (although to my knowledge we have ever used the Array->Hash conversion in any of our projects).
Had to use `.kind_of?(Array)` instead of `.respond_to?(:to_a)` since ruby Hashes responds to `to_a` and we don't want to convert all Hashes to Arrays.
close #71
> Do not convert Array to Hash when publishing

- .travis.yml
- lib/twingly/amqp/subscription.rb
From Bunny documentation, http://rubybunny.info/articles/concurrency.html#consumer_work_pools:
> Every channel maintains a fixed size thread pool used to dispatch
deliveries (messages pushed by RabbitMQ to consumers). By default every
pool has size of 1 to guarantee ordered message processing by default.
Close #68
> Change consumer thread default to 1 to match Bunny

- lib/twingly/amqp.rb
- lib/twingly/amqp/connection.rb
- lib/twingly/amqp/default_exchange_publisher.rb
- lib/twingly/amqp/message.rb
- lib/twingly/amqp/pinger.rb
- lib/twingly/amqp/publisher.rb
- lib/twingly/amqp/session.rb
- lib/twingly/amqp/subscription.rb
- lib/twingly/amqp/topic_exchange_publisher.rb
> Remove requires from individual components

- .github/workflows/ci.yml
Drop 2.5 since it's EoL since 2021-03-31.
> Test with latest Rubies

- lib/twingly/amqp/publisher.rb
- spec/integration/twingly/amqp/subscription_spec.rb
We previously assumed "publisher confirms" in RabbitMQ would wait for the messages to be consumed by a subscriber, but as it turns out, it only waits for the messages to be put onto a queue (there are some more details on it in [the documentation](https://www.rabbitmq.com/confirms.html#when-publishes-are-confirmed)).
I added a sleep to the code, so that we give the subscriber time to handle any messages before we continue with the test. I found no better way to do this that to add a sleep. The tests for Bunny uses sleeps too, for example see [this spec][1], so it seems like that's the best way.
I guess we could now remove the "pubisher confirms" feature from twingly-amqp, as we don't really need it. We added it so we didn't have to sleep (in #50), but it turns out we do need the sleep …
> Make sure Subscriber tests wait for messages to be consumed

- README.md
- lib/twingly/amqp/default_exchange_publisher.rb
- lib/twingly/amqp/subscription.rb
- lib/twingly/amqp/utilities.rb
- spec/amqp_queue_context.rb
- spec/integration/twingly/amqp/default_exchange_publisher_spec.rb
- spec/integration/twingly/amqp/subscription_spec.rb
- spec/integration/twingly/amqp/utilities_spec.rb
- twingly-amqp.gemspec
Now we support both classic queues (which is what we used before), and [quorum queues](https://www.rabbitmq.com/quorum-queues.html).
Only ["mirrored classic queues" are deprecated](https://www.rabbitmq.com/ha.html), not classic queues in general, so I opted to continue supporting classic queues in this gem, even though we'll most likely not use them once we have switched all of our production queues to quorum queues.
I added an extra argument to the classes that creates queues, which tells them what kind of queue to create. Based on that argument, the classes then either uses the `Channel#queue` or `Channel#quorum_queue` method to setup the queue. Those helper methods were added to Bunny in https://github.com/ruby-amqp/bunny/commit/0cae5f8766afc125c5cdd60e90b2b7962961b4c1
Related to …
> Use quorum queues by default instead of classic queues

- README.md
- lib/twingly/amqp/publisher.rb
- spec/integration/twingly/amqp/topic_exchange_publisher_spec.rb
This lets the `TopicExchangePublisher#publish` method override the previously set routing_key, which makes it possible to publish messages having different routing keys.
This also enables us to set [all other publishing options][1] per message, which before were only possible to change by reconfiguring the publisher.
Close #60
[1]: https://www.rubydoc.info/github/ruby-amqp/bunny/Bunny/Exchange#publish-instance_method
> Make it possible to override publishing options

- lib/twingly/amqp/subscription.rb
- spec/integration/twingly/amqp/subscription_spec.rb
- twingly-amqp.gemspec
Introduced an on_error callback in Twingly::AMQP::Subscription to handle channel errors, with a default behaviour of raising an exception if not set. Updated tests to cover the new callback and changed the Bunny dependency to require version >= 2.23.0.
In 2.23.0 https://github.com/ruby-amqp/bunny/releases/tag/2.23.0 `#on_error` is invoked when channel closes because of a delivery acknowledgement timeout
> Add channel error callback to Subscription
